'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class data_import

    '''<summary>
    '''btnCheckExceptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckExceptions As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tblExceptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblExceptions As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnAcceptData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAcceptData As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblDataAddedCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataAddedCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataDuplicateCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataDuplicateCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExceptionCountUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExceptionCountUpdated As Global.System.Web.UI.WebControls.Label
End Class
