'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class exceptions_counts

    '''<summary>
    '''btnCheckWksData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckWksData As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LVthisWeeksData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LVthisWeeksData As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''btnGetWklyDataCounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetWklyDataCounts As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LVCounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LVCounts As Global.System.Web.UI.WebControls.ListView
End Class
