'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class exceptions_duplicates

    '''<summary>
    '''lblDateRangeChecked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateRangeChecked As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateCountChecked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateCountChecked As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDuplicateCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDuplicateCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnDeleteDuplicates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteDuplicates As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblDataAddedCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataAddedCount As Global.System.Web.UI.WebControls.Label
End Class
